source 'https://rubygems.org'

# jekyll, which builds it all
  <<<<<<< snyk-fix-babeedf485fba393019a2d5e5ea8d495
gem 'jekyll', '~> 3.0', '>= 3.0.0'
  =======
gem 'jekyll', '~>3.6'
  >>>>>>> 0.3-stable

# JSON
gem 'json'

# SASS for CSS
gem 'sass'

# For `rake watch`
gem 'rb-fsevent'

# Redcarpet for Markdown
gem 'redcarpet'
 